{% set name = "google-cloud-appengine-logging" %}
{% set version = "1.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-appengine-logging-{{ version }}.tar.gz
  sha256: 37477ff25aaa2d3e085db834429c5c86d2783e604ebd7738c8692f361bc7c897

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - google-api-core-grpc >=1.31.5,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
    - proto-plus >=1.22.0,<2.0.0dev
    - protobuf >=3.20.2,<5.0.0dev

test:
  imports:
    - google.cloud.appengine_logging
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-appengine-logging
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://googleapis.dev/python/appenginelogging/latest/index.html
  dev_url: https://github.com/googleapis/python-appengine-logging
  summary: Python Client for Google Cloud Appengine Logging

extra:
  recipe-maintainers:
    - xylar
